name: suggest-unit-tests

on:
  issue_comment:
    types: [created]

jobs:
  comment-responder:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/suggest-unit-tests')
    steps:
      - name: 'Comment on PR'
        run: |
          PR=${{ github.event.issue.number }}
          gh pr diff $PR >& diff$PR
          gh api repos/dekimir/trino/contents/.github/bin/suggest_unit_tests.py --jq '.content' | base64 -d > script.py
          python3 script.py diff$PR | tee rec$PR
          gh pr comment $PR -F rec$PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          AWS_BEARER_TOKEN_BEDROCK: ${{ secrets.AWS_BEARER_TOKEN_BEDROCK }}
